---
title: "stat605_project"
author: "Andrew Hu"
date: "11/29/2020"
output: html_document
---
#read data
```{r}
data1 = read.csv("data_1.csv")
fare1 = read.csv("fare_1.csv")
summary(data1)
summary(fare1)
colnames(fare1)
colnames(data1)


data2 = read.csv("data_2.csv")
fare2 = read.csv("fare_2.csv")
```

#data clean
```{r}
library(dplyr)
library(chron)
taxi.1 = inner_join(data1,fare1,by = c("medallion","hack_license","vendor_id","pickup_datetime"))
colnames(taxi.1)
taxi.2 = inner_join(data2,fare2,by = c("medallion","hack_license","vendor_id","pickup_datetime"))

taxi.1$date = as.Date(taxi.1$pickup_datetime)
taxi.1$pickup_time = chron(times = format(as.POSIXct(taxi.1$pickup_datetime),format = "%H:%M:%S"))
taxi.2$date = as.Date(taxi.2$pickup_datetime)
taxi.2$pickup_time = chron(times = format(as.POSIXct(taxi.2$pickup_datetime),format = "%H:%M:%S"))

taxi.1.1 = taxi.1[-which(taxi.1$payment_type=="CSH"),]
plot(density(taxi.1.1$tip_amount))
taxi.2.1 = taxi.2[-which(taxi.2$payment_type=="CSH"),]
plot(density(taxi.2.1$tip_amount))

shapiro.test(taxi.1$tip_amount)
shapiro.test(taxi.1.1$tip_amount)
```
#models
```{r}
library(car)
library(lmtest)

#first model
fit = lm(tip_amount~trip_distance+trip_time_in_secs+vendor_id+pickup_time,data = taxi.1.1)
summary(fit)
vif(fit)
plot(fit)
bptest(fit)

#second model
fit1 = lm(tip_amount~trip_distance+I(trip_distance/trip_time_in_secs)+trip_time_in_secs+vendor_id+pickup_time,data = taxi.1.1)
summary(fit1)
vif(fit1)
plot(fit1)
bptest(fit1)
```

#accuracy of first model
```{r}
new = data.frame(trip_distance = taxi.2.1$trip_distance,
                 trip_time_in_secs = taxi.2.1$trip_time_in_secs,
                 vendor_id = taxi.2.1$vendor_id,
                 pickup_time = taxi.2.1$pickup_time)

mean((predict(fit,newdata = new)-taxi.2.1$tip_amount)**2)
plot(density(predict(fit,newdata = new)),main = "tip_amount")
lines(density(taxi.2.1$tip_amount),col = "red")
```

#heatmap
```{r}
taxi.12 = rbind(taxi.1,taxi.2)
class(taxi.12$pickup_datetime)
library(ggmap)
library(ggplot2)
register_google(key = "AIzaSyDUf9WsYILNDi5vsUOrNbQHMpebl0W2pac")
map <- get_map(location=c(lon=-73.935242,lat=40.730610),
               zoom=11, maptype='roadmap', color='bw')
ggmap(map, extent = "device") +
  geom_bin2d(data = taxi.12, aes(x = pickup_longitude,y = pickup_latitude),bins=100)

```
```{r}
area1 = read.csv("area_1.csv")
area2 = read.csv("area_2.csv")
area3 = read.csv("area_3.csv")
area4 = read.csv("area_4.csv")
area5 = read.csv("area_5.csv")
area6 = read.csv("area_6.csv")
area = bind_rows(area1,area2,area3,area4,area5,area6)
area = area[-which(area$area=="0 0"),]
length(unique(area$area))

area = separate(area,col = "area",sep = " ",into = c("lat","lon"))
area$lat = as.numeric(area$lat)
area$lon = as.numeric(area$lon)
```

```{r}
map <- get_map(location=c(lon=-73.935242,lat=40.730610),
               zoom=11, maptype='roadmap', color='bw')
ggmap(map, extent = "device") +
  geom_point(data = area, aes(x = lon,y = lat))

```
